/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.darrylsite.liferay.chat.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ChatUser service. Represents a row in the &quot;chatRoom_ChatUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.darrylsite.liferay.chat.model.impl.ChatUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.darrylsite.liferay.chat.model.impl.ChatUserImpl}.
 * </p>
 *
 * @author Darryl Kpizingui
 * @see ChatUser
 * @see com.darrylsite.liferay.chat.model.impl.ChatUserImpl
 * @see com.darrylsite.liferay.chat.model.impl.ChatUserModelImpl
 * @generated
 */
@ProviderType
public interface ChatUserModel extends BaseModel<ChatUser> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a chat user model instance should use the {@link ChatUser} interface instead.
	 */

	/**
	 * Returns the primary key of this chat user.
	 *
	 * @return the primary key of this chat user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this chat user.
	 *
	 * @param primaryKey the primary key of this chat user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this chat user.
	 *
	 * @return the ID of this chat user
	 */
	public long getId();

	/**
	 * Sets the ID of this chat user.
	 *
	 * @param id the ID of this chat user
	 */
	public void setId(long id);

	/**
	 * Returns the pseudo of this chat user.
	 *
	 * @return the pseudo of this chat user
	 */
	@AutoEscape
	public String getPseudo();

	/**
	 * Sets the pseudo of this chat user.
	 *
	 * @param pseudo the pseudo of this chat user
	 */
	public void setPseudo(String pseudo);

	/**
	 * Returns the description of this chat user.
	 *
	 * @return the description of this chat user
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this chat user.
	 *
	 * @param description the description of this chat user
	 */
	public void setDescription(String description);

	/**
	 * Returns the user ID of this chat user.
	 *
	 * @return the user ID of this chat user
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this chat user.
	 *
	 * @param userId the user ID of this chat user
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this chat user.
	 *
	 * @return the user uuid of this chat user
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this chat user.
	 *
	 * @param userUuid the user uuid of this chat user
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the avatar of this chat user.
	 *
	 * @return the avatar of this chat user
	 */
	@AutoEscape
	public String getAvatar();

	/**
	 * Sets the avatar of this chat user.
	 *
	 * @param avatar the avatar of this chat user
	 */
	public void setAvatar(String avatar);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ChatUser chatUser);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ChatUser> toCacheModel();

	@Override
	public ChatUser toEscapedModel();

	@Override
	public ChatUser toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}