/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.darrylsite.liferay.chat.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Contact service. Represents a row in the &quot;chatRoom_Contact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.darrylsite.liferay.chat.model.impl.ContactModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.darrylsite.liferay.chat.model.impl.ContactImpl}.
 * </p>
 *
 * @author Darryl Kpizingui
 * @see Contact
 * @see com.darrylsite.liferay.chat.model.impl.ContactImpl
 * @see com.darrylsite.liferay.chat.model.impl.ContactModelImpl
 * @generated
 */
@ProviderType
public interface ContactModel extends BaseModel<Contact> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a contact model instance should use the {@link Contact} interface instead.
	 */

	/**
	 * Returns the primary key of this contact.
	 *
	 * @return the primary key of this contact
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this contact.
	 *
	 * @param primaryKey the primary key of this contact
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this contact.
	 *
	 * @return the ID of this contact
	 */
	public long getId();

	/**
	 * Sets the ID of this contact.
	 *
	 * @param id the ID of this contact
	 */
	public void setId(long id);

	/**
	 * Returns the category of this contact.
	 *
	 * @return the category of this contact
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this contact.
	 *
	 * @param category the category of this contact
	 */
	public void setCategory(String category);

	/**
	 * Returns the priviledge of this contact.
	 *
	 * @return the priviledge of this contact
	 */
	public int getPriviledge();

	/**
	 * Sets the priviledge of this contact.
	 *
	 * @param priviledge the priviledge of this contact
	 */
	public void setPriviledge(int priviledge);

	/**
	 * Returns the status of this contact.
	 *
	 * @return the status of this contact
	 */
	public int getStatus();

	/**
	 * Sets the status of this contact.
	 *
	 * @param status the status of this contact
	 */
	public void setStatus(int status);

	/**
	 * Returns the chat user ID of this contact.
	 *
	 * @return the chat user ID of this contact
	 */
	public long getChatUserId();

	/**
	 * Sets the chat user ID of this contact.
	 *
	 * @param chatUserId the chat user ID of this contact
	 */
	public void setChatUserId(long chatUserId);

	/**
	 * Returns the chat user uuid of this contact.
	 *
	 * @return the chat user uuid of this contact
	 */
	public String getChatUserUuid();

	/**
	 * Sets the chat user uuid of this contact.
	 *
	 * @param chatUserUuid the chat user uuid of this contact
	 */
	public void setChatUserUuid(String chatUserUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Contact contact);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Contact> toCacheModel();

	@Override
	public Contact toEscapedModel();

	@Override
	public Contact toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}