/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.darrylsite.liferay.chat.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Lounge service. Represents a row in the &quot;chatRoom_Lounge&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.darrylsite.liferay.chat.model.impl.LoungeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.darrylsite.liferay.chat.model.impl.LoungeImpl}.
 * </p>
 *
 * @author Darryl Kpizingui
 * @see Lounge
 * @see com.darrylsite.liferay.chat.model.impl.LoungeImpl
 * @see com.darrylsite.liferay.chat.model.impl.LoungeModelImpl
 * @generated
 */
@ProviderType
public interface LoungeModel extends BaseModel<Lounge> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lounge model instance should use the {@link Lounge} interface instead.
	 */

	/**
	 * Returns the primary key of this lounge.
	 *
	 * @return the primary key of this lounge
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lounge.
	 *
	 * @param primaryKey the primary key of this lounge
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this lounge.
	 *
	 * @return the ID of this lounge
	 */
	public long getId();

	/**
	 * Sets the ID of this lounge.
	 *
	 * @param id the ID of this lounge
	 */
	public void setId(long id);

	/**
	 * Returns the name of this lounge.
	 *
	 * @return the name of this lounge
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this lounge.
	 *
	 * @param name the name of this lounge
	 */
	public void setName(String name);

	/**
	 * Returns the priviledge of this lounge.
	 *
	 * @return the priviledge of this lounge
	 */
	public int getPriviledge();

	/**
	 * Sets the priviledge of this lounge.
	 *
	 * @param priviledge the priviledge of this lounge
	 */
	public void setPriviledge(int priviledge);

	/**
	 * Returns the user ID of this lounge.
	 *
	 * @return the user ID of this lounge
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this lounge.
	 *
	 * @param userId the user ID of this lounge
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this lounge.
	 *
	 * @return the user uuid of this lounge
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this lounge.
	 *
	 * @param userUuid the user uuid of this lounge
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this lounge.
	 *
	 * @return the create date of this lounge
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this lounge.
	 *
	 * @param createDate the create date of this lounge
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this lounge.
	 *
	 * @return the modified date of this lounge
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this lounge.
	 *
	 * @param modifiedDate the modified date of this lounge
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Lounge lounge);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Lounge> toCacheModel();

	@Override
	public Lounge toEscapedModel();

	@Override
	public Lounge toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}